spring.profiles.active=dev

# Adicione esta linha com a chave que voc� obteve no site do TMDB
tmdb.api.key=SUA_CHAVE_AQUI

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n

